config/routes.rb
Rails.application.routes.draw do
  resources :samples
  resources :samples
  resources :samples
  root to: 'preview#show'
end

app/models/sample.rb
class Sample < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/preview_controller.rb
class PreviewController < ApplicationController
  def show
    @pre_source = %q{#include<stdio>

int main() {
    puts("Hello 世界!");
    return 0;
}
}
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(:title, :body, :published)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/preview_helper.rb
module PreviewHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SanitizeCssOnline
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/preview/show.html.haml
%h1 Header
%header
  %ul
    %li Coffee
    %li Tea
    %li Milk


%h1 Navigation
%h2 Unordered list
%nav
  %ul
    %li Coffee
    %li Tea
    %li Milk

%h2 Ordered list
%nav
  %ol
    %li Spam
    %li Ham
    %li Egg

%h1 Heading 1
%h2 Heading 2
%h3 Heading 3

%h1 Text
%p
  Lorem ipsum dolor sit amet,
  %a{href: 'http://10up.github.io/sanitize.css/'} consectetur adipiscing elit,
  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
%p
  %small
    Lorem ipsum dolor sit amet,
    %a{href: 'http://10up.github.io/sanitize.css/'} consectetur adipiscing elit,
    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

%p
  あのイーハトーヴォのすきとおった風、
  %a{href: 'http://10up.github.io/sanitize.css/'} 夏でも底に冷たさをもつ青いそら、
  うつくしい森で飾られたモリーオ市、郊外のぎらぎらひかる草の波。
%p
  %small
    あのイーハトーヴォのすきとおった風、
    %a{href: 'http://10up.github.io/sanitize.css/'} 夏でも底に冷たさをもつ青いそら、
    うつくしい森で飾られたモリーオ市、郊外のぎらぎらひかる草の波。

%h1 List

%h2 Unordered list
%ul
  %li Coffee
  %li Tea
  %li Milk

%h2 Ordered list
%ol
  %li Spam
  %li Ham
  %li Egg

%h2 Definition list
%dl
  %dt Coffee
  %dd black hot drink
  %dt Milk
  %dd white cold drink

%h1 Form

%form
  %p
    %label
      名前：
      %input{:name => "name", :size => "40", :type => "text"}/
  %p
    %label
      血液型：
      %select{:name => "blood"}
        %option{:value => "A"} A型
        %option{:value => "B"} B型
        %option{:value => "O"} O型
        %option{:value => "AB"} AB型
  %fieldset
    %legend 性別
    %p
      %label
        %input{:name => "sex", :type => "radio", :value => "male"} 男
    %p
      %label
        %input{:name => "sex", :type => "radio", :value => "female"} 女
  %fieldset
    %legend 趣味
    %p
      %label
        %input{:name => "hobby", :type => "checkbox", :value => "sports"} スポーツ
    %p
      %label
        %input{:name => "hobby", :type => "checkbox", :value => "reading"} 読書
    %p
      %label
        %input{:name => "hobby", :type => "checkbox", :value => "music"} 音楽
    %p
      %label
        %input{:name => "hobby", :type => "checkbox", :value => "travel"} 旅行
  %p
    %label
      情報源
      %select{multiple: 'multiple'}
        %option 新聞
        %option ラジオ
        %option テレビ
  %p
    %label
      コメント：
      %br
        %textarea{:cols => "40", :name => "comments", :rows => "2"}
  %p
    %input{:type => "submit", :value => "送信"}
      %input{:type => "reset", :value => "リセット"}/

%h1 Table
%table
  %thead
    %tr
      %th Firstname
      %th Lastname
      %th Points
  %tbody
    %tr
      %td Jill
      %td Smith
      %td 50
    %tr
      %td Eve
      %td Jackson
      %td 94
    %tr
      %td John
      %td Doe
      %td 80

%h1 Code
code
%code
  Hello world!

pre:
%pre= @pre_source

%h1 Blockquote
%blockquote
  Lorem ipsum dolor sit amet,
  %a{href: 'http://10up.github.io/sanitize.css/'} consectetur adipiscing elit,
  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

%blockquote
  あのイーハトーヴォのすきとおった風、
  %a{href: 'http://10up.github.io/sanitize.css/'} 夏でも底に冷たさをもつ青いそら、
  うつくしい森で飾られたモリーオ市、郊外のぎらぎらひかる草の波。

app/views/samples/_form.html.haml
= form_for @sample do |f|
  - if @sample.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sample.errors.count, "error")} prohibited this sample from being saved:"
      %ul
        - @sample.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :published
    = f.check_box :published
  .actions
    = f.submit 'Save'

app/views/samples/edit.html.haml
%h1 Editing sample

= render 'form'

= link_to 'Show', @sample
\|
= link_to 'Back', samples_path

app/views/samples/index.html.haml
%h1 Listing samples

%table
  %thead
    %tr
      %th Title
      %th Body
      %th Published
      %th
      %th
      %th

  %tbody
    - @samples.each do |sample|
      %tr
        %td= sample.title
        %td= sample.body
        %td= sample.published
        %td= link_to 'Show', sample
        %td= link_to 'Edit', edit_sample_path(sample)
        %td= link_to 'Destroy', sample, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sample', new_sample_path

app/views/samples/new.html.haml
%h1 New sample

= render 'form'

= link_to 'Back', samples_path

app/views/samples/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @sample.title
%p
  %b Body:
  = @sample.body
%p
  %b Published:
  = @sample.published

= link_to 'Edit', edit_sample_path(@sample)
\|
= link_to 'Back', samples_path